apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatassistant.appSecretName" . }}
  labels:
    {{- include "chatassistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.llmApiKey }}
  LLM_API_KEY: {{ .Values.llmApiKey | quote }}
  {{- end }}
  {{- if .Values.embedApiKey }}
  EMBED_API_KEY: {{ .Values.embedApiKey | quote }}
  {{- end }}
  {{- if .Values.railApiKey }}
  RAIL_API_KEY: {{ .Values.railApiKey | quote }}
  {{- end }}
